name: rest_apis_porject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  gradient_borders: ^1.0.1
  get:
  http:
  provider:
  lottie:
  permission_handler: ^11.0.1
  flutter_sound: ^9.2.13
  intl: ^0.18.0
  path_provider: ^2.1.2
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.9
  share_plus: ^11.0.0

flutter_gen:
  output: lib/gen/
  integrations:
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/lottie/

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
